### ISSUE TITLE
Thanks

### ISSUE THREAD

**Issue by humphreygaming** [BigQuantumMan/Surviv.io-Cheat#1]
Thank you for continuing zbot's legacy

**Comment by IceHacks** [comment]
Yes, 'twas very nice of you.

**Comment by BigQuantumMan** [comment]
In my free time I will develop this project.
I hope that another patch will not come out too soon :)

**Comment by humphreygaming** [comment]
@BigQuantumMan i'm sorry to disapoint you, but an update will come out most likely today at 8:00 PST :(

**Comment by BigQuantumMan** [comment]
@humphreygaming 
I meant additional security, not a simple update;)

**Comment by BigQuantumMan** [comment]
@humphreygaming 
I meant additional security, not a simple update ;)
