### ISSUE TITLE
Performance Update

### ISSUE THREAD

**Issue by IceHacks** [BigQuantumMan/Surviv.io-Cheat#13]
I found  (when I made cheats) that surviv.io had a variable called "`inputMsgTimeout`" inside the game object and when setting that to `0` it vastly decreased the game lag. And whenever I set it back to 1 it was really laggy again. I never proved really that it had an effect but I always felt a difference in response time. Adding it won't hurt :)

Also deobfuscating your code would make it so the GitHub community (including me) could help develop this cheat so you don't have to all by yourself (I also wouldn't have to keep opening issues).

My code went simply like this `game.inputMsgTimeout = 0;` however you could probably make a replacer for `app.xxx.js` to do the same thing.

Example:
```
{
    name: "input timeout",
    from: /this\.inputMsgTimeout=1/g,
    to: "this.inputMsgTimeout=0"
}
```

I hope you add it. Looking at `app.xxx.js` it seems I was right. The reason I want this so much is because where I live surviv.io has 100ms ping.

**Comment by BigQuantumMan** [comment]
I understand, but looking at other such projects too many people do not help.
There will be maybe 2-3 such people.

However, soon you will be able to add your own plugins.
However, I plan to add the ability to edit plugins, but only them.

**Comment by BigQuantumMan** [comment]
https://github.com/BigQuantumMan/Surviv.io-Cheat/commit/b7c8f6a5918f1c4676d0025495aafc22b3743b50

**Comment by IceHacks** [comment]
A plugin idea is great :) I had it in my first cheat. Awesome thanks.
