### ISSUE TITLE
Squaders Rights!

### ISSUE THREAD

**Issue by humphreygaming** [BigQuantumMan/Surviv.io-Cheat#14]
Woods modes has been moved from solos to squads, so naturally, this hack is patched (pray that it won't freeze)

**Comment by drogga** [comment]
It spams errors now and this affects the framerate negatively.

**Comment by BigQuantumMan** [comment]
I am currently on the road. I will fix it in about 2 hours...

**Comment by drogga** [comment]
No problem @BigQuantumMan 
Upon further inspection, repeat fire stopped functioning, also the two options that generate errors are draw lines to players and air drop tracking. Everything else seems to work as before.

However, for me grenade color and size are not working, both say "false" no matter the slider's position.

Side note: Is it possible to give loot trees, rocks and barrels unique colors like in zbot473's version, or would that cause the hack to freeze like Kalaborative's?
Cuz I'm missing the transparent trees and bushes :P

**Comment by BigQuantumMan** [comment]
https://github.com/BigQuantumMan/Surviv.io-Cheat/commit/f54399a361f3e6e1c6060878ee4b9be4484852fb

@drogga 
1. I will fix the problem with grenades.
2. Ok, but in my free time.
