### ISSUE TITLE
Auto aim broken/need toggle fire auto aim

### ISSUE THREAD

**Issue by ninjaman911** [BigQuantumMan/Surviv.io-Cheat#16]
When auto aim is on it just gets stuck in one direction and fires, can't move the player's direction. 

Also there should be a feature to disable auto firing on an enemy or for you to hold a key for auto aim firing to occur [like right mouse click ofc] [Kalaborative/survivio-plus for reference has this but that mod is broken], I don't want it to immediately fire at the enemy when it sees him. Sometimes they're behind trees and buildings and I just waste ammo. Not sure why there are no toggles of the sort through key binds in this mod. 

Thank You for the work.

**Comment by BigQuantumMan** [comment]
If you want to turn off automatic shooting:
![image](https://user-images.githubusercontent.com/49454024/56462265-9ec39800-63c0-11e9-8715-7c53bf4ef4fc.png)
Strange, but I have no problems. Could you send a picture with errors from the console?
What extension version do you have?

**Comment by BigQuantumMan** [comment]
If you want to turn off automatic shooting:
![image](https://user-images.githubusercontent.com/49454024/56462279-e77b5100-63c0-11e9-8a31-992770b1cd8e.png)
Strange, but I have no problems. Could you send a picture with errors from the console?
What extension version do you have?
