### ISSUE TITLE
 Trojan-Downloader.JS.Agent

### ISSUE THREAD

**Issue by fan02792** [BigQuantumMan/Surviv.io-Cheat#3]
Trojan-Downloader.JS.Agent https://www.virustotal.com/gui/file/eb08c4261119edc4e2c469aa01f9655fa9b82ddc0ab81eac8c2a93ea9bbb09be/detection

**Comment by BigQuantumMan** [comment]
The fact that 1 out of 58 detected something, it does not mean that it is actually a virus ... I had the same problem when downloading eg cheat iceHack.

**Comment by BigQuantumMan** [comment]
That's why there are 58 engines out there that test it, not 1...
Such an effect can be obtained after code obfuscation...

**Comment by BigQuantumMan** [comment]
https://www.virustotal.com/pl/file/554b26b844543d33e3c921a8c98e466867a312a2e9e22ebfaa14cb60e31097d2/analysis/1555434655/

I did not change anything, just re-read the source code. Next time, please learn how code analysis systems work.

**Comment by BigQuantumMan** [comment]
https://www.npmjs.com/package/javascript-obfuscator
