### ISSUE TITLE
Clicked "Download this repo as a ZIP file." Got "Not Found"

### ISSUE THREAD

**Issue by ninjaman911** [BigQuantumMan/Surviv.io-Cheat#5]
**Describe the bug**

**Screenshots**
Add photos of bugs from the console, if it is closely related to it.

**Desktop (please complete the following information):**
 - Browser version
 - Extension version [e.g. 1.0.70]

**Expected behavior**

**Additional context**

**Comment by BigQuantumMan** [comment]
I fixed it, but you could use this button:
![image](https://user-images.githubusercontent.com/49454024/56245804-91e13480-60a0-11e9-8370-cbde402c1111.png)
