### ISSUE TITLE
I got some features for you. (and the code for them)

### ISSUE THREAD

**Issue by IceHacks** [BigQuantumMan/Surviv.io-Cheat#6]
I am gonna stop updating my cheat now as I am too busy so here are some things to make yours better that were in mine.

Ceilings (won't cause freeze):
```
{
	"from": /ceilingSprite:"(.*?)"/g,
	"to": 'ceilingSprite:""'
}, {
	"from": /sprite:"map-([a-zA-Z-]*?)-ceiling([-0-9]*?[a-z]?)\.img",/g,
	"to": 'sprite:"",'
},
```

Scope changes (optional):
```
{
	"from": '"1xscope":28',
	"to": '"1xscope":36'
}, {
	"from": '"2xscope":36',
	"to": '"2xscope":48'
}, {
	"from": '"4xscope":48',
	"to": '"4xscope":68'
}, {
	"from": '"8xscope":68',
	"to": '"8xscope":78'
}
```

**I also have a variable fetching script for you that is too big to paste here. Tell me if you need it.**

feel free to not use any of this if you don't want to

**Comment by IceHacks** [comment]
Oh also for auto emote I have that too.

**Comment by IceHacks** [comment]
Of course, this was all designed for my cheat so you will have to edit it some.

**Comment by reflexin** [comment]
> Of course, this was all designed for my cheat so you will have to edit it some.

So your hack will no longer be supported? The paid version?

**Comment by IceHacks** [comment]
> > Of course, this was all designed for my cheat so you will have to edit it some.
> 
> So your hack will no longer be supported? The paid version?

until further notice it won't.

**Comment by TheSatanicAngeI** [comment]
@IceHacks Damn that sucks

**Comment by BigQuantumMan** [comment]
Thank you, I will add these functions in my free time.

**Comment by BigQuantumMan** [comment]
https://github.com/BigQuantumMan/Surviv.io-Cheat/commit/a3f0f6cd785367a013cea5fa197a3a09fa7a50b6

Ok, added.

**Comment by IceHacks** [comment]
Awesome ;)

if you ever need anything just ask :)

**Comment by BigQuantumMan** [comment]
Ok, thanks ;)
