### ISSUE TITLE
Can't shoot with secondary weapon

### ISSUE THREAD

**Issue by reflexin** [BigQuantumMan/Surviv.io-Cheat#7]
I can only shoot with my primary weapon. When I try to shoot with my secondary weapon, it doesn't allow me to shoot and automatically changes my weapon back to my primary one.

It should allow me to shoot.

**Comment by BigQuantumMan** [comment]
Have you changed the key assignment? I need more information....

**Comment by reflexin** [comment]
> Have you changed the key assignment? I need more information....

No, I haven't touched it
