### ISSUE TITLE
can't team emote

### ISSUE THREAD

**Issue by Brushfiremage62** [BigQuantumMan/Surviv.io-Cheat#8]
Can't team emote to tell what kind of ammo or if i need meds 
.

**Comment by BigQuantumMan** [comment]
Emotes are available after pressing the B key(instead right mouse key).
Or additionally a b + c combination.

**Comment by BigQuantumMan** [comment]
Emotes are available after pressing the B (or B + C) key.

**Comment by Brushfiremage62** [comment]
I fixed it, it was binded to wrong thing
